name=input("enter your name: ")
surname=input("enter your surname: ")
age=input("enter your age: ")
num1=input("enter number1: ")
num2=input("enter number2: ")
print(name)
print(surname)
print(age)
print(num1)
print(num2)


print(type(name))
print(type(surname))
print(type(age))
print(type(num1))
print(type(num2))